---
- name: Install rclone
  hosts: nuc
  become: true
  vars_files:
    - secret.yml

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install rclone package
      apt:
        name: rclone

    - name: Verify rclone installation
      command: rclone --version
      become: no

    - name: Create rclone config file
      copy:
        content: |
          [shared]
          type = dropbox
          client_id = {{ dropbox_app_key }}
          client_secret = {{ dropbox_app_secret }}
          token = {{ dropbox_access_token }}
        dest: /home/rex/.config/rclone/rclone.conf
      become: no
