---
- name: Install Docker
  hosts: nuc
  become: true

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name: ['ca-certificates', 'curl', 'gnupg']

    - name: Create keyrings directory
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        keyring: /etc/apt/keyrings/docker.gpg

    - name: Add Docker APT repository
      apt_repository:
        repo: deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        filename: docker

    - name: Update apt cache again with new repository
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: ['docker-ce', 'docker-ce-cli', 'containerd.io', 'docker-buildx-plugin', 'docker-compose-plugin']

    - name: Ensure Docker service is running
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Pull hello-world Docker image
      docker_image:
        name: hello-world
        source: pull

    - name: Run hello-world container
      docker_container:
        name: hello-world-container
        image: hello-world
        state: started

    - name: Remove hello-world container
      docker_container:
        name: hello-world-container
        state: absent
