---
- name: Resize Logical Volume and Filesystem
  hosts: nuc
  become: yes

  tasks:
    - name: Resize Logical Volume
      command: >
        lvresize -vl +100%FREE /dev/mapper/ubuntu--vg-ubuntu--lv

    - name: Resize Filesystem
      command: >
        resize2fs -p /dev/mapper/ubuntu--vg-ubuntu--lv
