- name: Set up Immich
  hosts: nuc
  become: yes
  vars_files:
    - secret.yml

  tasks:
    - name: Create bind mounts
      file:
        path: "{{ item }}"
        state: directory
      loop:
        - /home/rex/8tb/immich
        - /home/rex/8tb/immich/model-cache
      become: no

    - name: Copy files
      copy:
        src: "{{ item }}"
        dest: "/home/rex/8tb/{{ item }}"
      loop:
        - immich/.env
        - immich/docker-compose.yml

    - name: Run docker compose
      command: docker compose up -d
      args:
        chdir: /home/rex/8tb/immich
