---
- import_playbook: install_rclone.yml

- name: Set up Jellyfin
  hosts: nuc
  become: yes

  tasks:
    - name: Create jellyfin/
      file:
        path: /home/rex/jellyfin
        state: directory
      become: no

    - name: Create jellyfin/config/
      file:
        path: /home/rex/jellyfin/config
        state: directory
      become: no

    - name: Create jellyfin/cache/
      file:
        path: /home/rex/jellyfin/cache
        state: directory
      become: no

    - name: Create jellyfin/movies/
      file:
        path: /home/rex/jellyfin/movies
        state: directory
      become: no

    - name: Create jellyfin/shows/
      file:
        path: /home/rex/jellyfin/shows
        state: directory
      become: no

    - name: Copy files using rclone - movies
      command: rclone copy shared:/YingTing\ Wu/Rex/Jellyfin/Movies /home/rex/jellyfin/movies
      become: no
      tags: copy

    - name: Copy files using rclone - shows
      command: rclone copy shared:/YingTing\ Wu/Rex/Jellyfin/Shows /home/rex/jellyfin/shows
      become: no
      tags: copy

    - name: Create Jellyfin container
      docker_container:
        name: jellyfin
        image: jellyfin/jellyfin
        user: "{{ ansible_user_uid }}:{{ ansible_user_gid }}"
        network_mode: host
        volumes:
          - /etc/hosts:/tmp/hosts
          - /home/rex/jellyfin/config:/config
          - /home/rex/jellyfin/cache:/cache
          - /home/rex/jellyfin/movies:/movies
          - /home/rex/jellyfin/shows:/shows
        restart_policy: unless-stopped
        env:
          JELLYFIN_PublishedServerUrl: http://nuc.rexyuan.com
        command: bash -c "cat /tmp/hosts >> /etc/hosts"
