---
- name: Set up Home Assistant
  hosts: nuc
  become: yes

  tasks:
    - name: Create bind mounts
      file:
        path: "{{ item }}"
        state: directory
      loop:
        - /home/rex/home-assistant
        - /home/rex/home-assistant/config
      become: no

    - name: Start Home Assistant Docker container
      docker_container:
        name: home-assistant
        image: "ghcr.io/home-assistant/home-assistant:stable"
        volumes:
          - /home/rex/home-assistant/config:/config
          - /etc/localtime:/etc/localtime:ro
        restart_policy: unless-stopped
        privileged: true
        network_mode: host

    - name: Install HACS
      community.docker.docker_container_exec:
        container: home-assistant
        command: bash -c 'wget -O - https://get.hacs.xyz | bash -'

    - name: Restart container
      docker_container:
        name: home-assistant
        restart: true
