---
- name: Set up ddns
  hosts: nuc

  tasks:
    - name: Clone Git Repository
      git:
        repo: https://github.com/RexYuan/FuXuan.git
        dest: /home/rex/Projects/FuXuan

    - name: Create logs/
      file:
        path: /home/rex/logs
        state: directory

    - name: Copy secret.sh
      copy:
        src: /Users/rexyuan/Projects/FuXuan/secret.sh
        dest: /home/rex/Projects/FuXuan/secret.sh

    - name: Check if ddns.sh Exists
      stat:
        path: /home/rex/Projects/FuXuan/ddns.sh
      register: ddns_script_exist
      failed_when: not ddns_script_exist.stat.exists

    - name: Add Cron Job
      cron:
        name: "ddns_logging"
        minute: "0"
        hour: "*/2"
        job: "echo -n \"[$(date)] \" >> /home/rex/logs/ddns.log; /home/rex/Projects/FuXuan/ddns.sh >> /home/rex/logs/ddns.log"
