---
- name: Set up Pi-hole
  hosts: nuc
  become: yes
  vars_files:
    - secret.yml

  tasks:
    - name: Update resolv.conf symlink
      file:
        src: /run/systemd/resolve/resolv.conf
        dest: /etc/resolv.conf
        state: link

    - name: Disable DNSStubListener in resolved.conf
      lineinfile:
        dest: /etc/systemd/resolved.conf
        insertafter: '^#DNSStubListener='
        line: 'DNSStubListener=no'
      notify: Restart systemd-resolved

    - name: Create bind mounts
      file:
        path: "{{ item }}"
        state: directory
      loop:
        - /home/rex/pihole
        - /home/rex/pihole/etc-pihole
        - /home/rex/pihole/etc-dnsmasq.d
      become: no

    - name: Start Pihole container
      docker_container:
        name: pihole
        image: pihole/pihole:latest
        ports:
          - "53:53/tcp"
          - "53:53/udp"
          - "67:67/udp"
          - "8888:80/tcp"
        env:
          TZ: 'Asia/Taipei'
          WEBPASSWORD: '{{ pihole_key }}'
        volumes:
          - '/home/rex/pihole/etc-pihole:/etc/pihole'
          - '/home/rex/pihole/etc-dnsmasq.d:/etc/dnsmasq.d'
        capabilities:
          - NET_ADMIN
        restart_policy: unless-stopped

  handlers:
    - name: Restart systemd-resolved
      systemd:
        name: systemd-resolved
        state: restarted
