---
- name: Set up Jellyfin
  hosts: nuc
  become: yes

  tasks:
    - name: Create bind mounts
      file:
        path: "{{ item }}"
        state: directory
      loop:
        - /home/rex/8tb/jellyfin
        - /home/rex/8tb/jellyfin/config
        - /home/rex/8tb/jellyfin/cache
        - /home/rex/8tb/jellyfin/movies
        - /home/rex/8tb/jellyfin/shows
        - /home/rex/8tb/jellyfin/fonts
      become: no

    - name: Copy fonts
      copy:
        src: "{{ item }}"
        dest: /home/rex/8tb/jellyfin/fonts
      with_fileglob:
        - "/Users/rexyuan/Projects/FuXuan/Noto_Sans_TC/static/*"

    - name: Create Jellyfin container
      docker_container:
        name: jellyfin
        image: jellyfin/jellyfin
        user: "{{ ansible_user_uid }}:{{ ansible_user_gid }}"
        ports:
          - "8096:8096/tcp"
        volumes:
          - /etc/hosts:/tmp/hosts
          - /home/rex/8tb/jellyfin/config:/config
          - /home/rex/8tb/jellyfin/cache:/cache
          - /home/rex/8tb/jellyfin/movies:/movies
          - /home/rex/8tb/jellyfin/shows:/shows
          - /home/rex/8tb/jellyfin/fonts:/fonts
        devices:
          - /dev/dri:/dev/dri
        restart_policy: unless-stopped
        command: bash -c "cat /tmp/hosts >> /etc/hosts"
