---
- name: Set up Jellyfin
  hosts: nuc
  become: yes
  vars_files:
    - secret.yml

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install rclone package
      apt:
        name: rclone

    - name: Verify rclone installation
      command: rclone --version
      become: no

    - name: Create rclone config file
      copy:
        content: |
          [shared]
          type = dropbox
          client_id = {{ dropbox_app_key }}
          client_secret = {{ dropbox_app_secret }}
          token = {{ dropbox_access_token }}
        dest: /home/rex/.config/rclone/rclone.conf
      become: no

    - name: Copy files using rclone - videos
      command: rclone copy shared:/YingTing\ Wu/Rex/Jellyfin/Videos /home/rex/jellyfin/videos
      become: no
      tags: copy

    - name: Copy files using rclone - movies
      command: rclone copy shared:/YingTing\ Wu/Rex/Jellyfin/Movies /home/rex/jellyfin/movies
      become: no
      tags: copy

    - name: Copy files using rclone - shows
      command: rclone copy shared:/YingTing\ Wu/Rex/Jellyfin/Shows /home/rex/jellyfin/shows
      become: no
      tags: copy

    - name: Copy files using rclone - books
      command: rclone copy shared:/YingTing\ Wu/Rex/Jellyfin/Books /home/rex/jellyfin/books
      become: no
      tags: copy

    - name: Create Jellyfin container
      docker_container:
        name: jellyfin
        image: jellyfin/jellyfin
        user: "{{ ansible_user_uid }}:{{ ansible_user_gid }}"
        network_mode: host
        volumes:
          - /etc/hosts:/tmp/hosts
          - /home/rex/jellyfin/config:/config
          - /home/rex/jellyfin/cache:/cache
          - /home/rex/jellyfin/videos:/videos
          - /home/rex/jellyfin/movies:/movies
          - /home/rex/jellyfin/shows:/shows
          - /home/rex/jellyfin/books:/books
        restart_policy: unless-stopped
        env:
          JELLYFIN_PublishedServerUrl: http://nuc.rexyuan.com
        command: bash -c "cat /tmp/hosts >> /etc/hosts"
