---
- import_playbook: install_rclone.yml
  tags: copy

- name: Set up Jellyfin
  hosts: nuc
  become: yes

  tasks:
    - name: Create bind mounts
      file:
        path: "{{ item }}"
        state: directory
      loop:
        - /home/rex/jellyfin
        - /home/rex/jellyfin/config
        - /home/rex/jellyfin/cache
        - /home/rex/jellyfin/movies
        - /home/rex/jellyfin/shows
        - /home/rex/jellyfin/fonts
      become: no

    - name: Copy files using rclone - movies
      command: rclone copy shared:/YingTing\ Wu/Rex/Jellyfin/Movies /home/rex/jellyfin/movies
      become: no
      tags: copy

    - name: Copy files using rclone - shows
      command: rclone copy shared:/YingTing\ Wu/Rex/Jellyfin/Shows /home/rex/jellyfin/shows
      become: no
      tags: copy

    - name: Copy fonts
      copy:
        src: "{{ item }}"
        dest: /home/rex/jellyfin/fonts
      with_fileglob:
        - "/Users/rexyuan/Projects/FuXuan/Noto_Sans_TC/static/*"

    - name: Create Jellyfin container
      docker_container:
        name: jellyfin
        image: jellyfin/jellyfin
        user: "{{ ansible_user_uid }}:{{ ansible_user_gid }}"
        # ports:
        #   - "8096:8096/tcp"
        # network_mode: host
        # 8096
        volumes:
          - /etc/hosts:/tmp/hosts
          - /home/rex/jellyfin/config:/config
          - /home/rex/jellyfin/cache:/cache
          - /home/rex/jellyfin/movies:/movies
          - /home/rex/jellyfin/shows:/shows
          - /home/rex/jellyfin/fonts:/fonts
        restart_policy: unless-stopped
        env:
          JELLYFIN_PublishedServerUrl: http://nuc.rexyuan.com
        command: bash -c "cat /tmp/hosts >> /etc/hosts"
        network_mode: bridge
        networks:
          - name: home_bridge
